# 应用程序配置文件示例
# 请复制此文件为 config.toml 并根据实际环境修改配置值

[database]
# 数据库主机地址
host = "localhost"
# 数据库用户名
user = "your_username"
# 数据库密码
password = "your_password"
# 数据库名称
name = "your_database"
# 数据库端口
port = "5432"

[server]
# 服务器URL
url = "localhost"
# 服务器端口
port = "3000"

[jwt]
# JWT密钥，生产环境请使用强密码
secret = "your_jwt_secret_key_here"